---
- name: Get the container registry credentials
  changed_when: true
  check_mode: false
  ansible.builtin.command:
    cmd: aws ecr get-login-password --region {{ container_registry.region }}
  environment:
    AWS_ACCESS_KEY_ID: "{{ container_registry.access_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ container_registry.secret_key }}"
  register: ecr_login_password

- name: Set the docker registry credentials
  ansible.builtin.set_fact:
    docker_registry_auth: >-
      aws:{{ ecr_login_password.stdout }}

- name: Set the docker registry auth configuration
  ansible.builtin.set_fact:
    docker_registry_auth_data: >
      {
        "auths": {
          "{{ container_registry.server }}": {
            "auth": "{{ docker_registry_auth | b64encode }}"
          }
        }
      }

- name: Create the K8s secret to access the registry
  kubernetes.core.k8s:
    state: present
    context: "{{ ansible_kubectl_context }}"
    namespace: default
    definition:
      kind: Secret
      apiVersion: v1
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: "ecr-{{ project }}"
      data:
        .dockerconfigjson: "{{ docker_registry_auth_data | to_json | b64encode }}"
