---
- name: Ensure ConfigMap object is present
  kubernetes.core.k8s:
    state: present
    context: "{{ ansible_kubectl_context }}"
    namespace: default
    definition:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: "{{ k8s_objects.configmap }}"
        labels:
          app.caden.io/name: "{{ project }}"
          app.caden.io/service: "{{ project }}"
          app.caden.io/managed-by: "ansible"
          tags.datadoghq.com/env: "{{ env }}"
          tags.datadoghq.com/service: "{{ project }}"
          tags.datadoghq.com/version: "{{ k8s_objects.app_version }}"
          admission.datadoghq.com/enabled: "true"
          admission.datadoghq.com/config.mode: "socket"
      data: "{{ environment_variables_configs }}"
