---
- hosts: "{{ target }}"
  gather_facts: false
  connection: local

  collections:
    - kubernetes.core

  roles:
    - role: authentication
    - role: container_registry
    - role: container_image
    - role: env_vars
    - role: web_server
