---
- name: Update kubeconfig
  delegate_to: localhost
  ansible.builtin.shell:
    cmd:
      aws --region {{ container_registry.region }}
      eks update-kubeconfig
      --name {{ k8s_cluster_name }}
