name: deploy_uber

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v20[2-9][0-9][0-1][0-9][0-3][0-9]-[0-9][0-9]
      - v20[2-9][0-9][0-1][0-9][0-3][0-9]-[0-9][0-9]-rc
      - v20[2-9][0-9][0-1][0-9][0-3][0-9]-[0-9][0-9]-uat
    paths:
      - '**.xml'
      - '.github/workflows/*transformers*.yml'
      - 'ansible/**'
      - 'Dockerfile'
      - 'src/main/java/io/caden/transformers/config/**'
      - 'src/main/java/io/caden/transformers/transformersApplication.java'
      - 'src/main/java/io/caden/transformers/shared/**'
      - 'src/main/java/io/caden/transformers/uber/**'
      - 'src/main/resources/application.properties'

env:
  ANSIBLE_FORCE_COLOR: '1'
  PY_COLORS: '1'

jobs:
  deploy:
    uses: ./.github/workflows/deploy_base.yml
    with:
      intake: 'uber'
    secrets:
      ansible_vault_password: '${{ secrets.ANSIBLE_VAULT_PASSWORD }}'
