name: deploy_tests

on:
  pull_request:
    branches:
      - main

env:
  ANSIBLE_FORCE_COLOR: '1'
  PY_COLORS: '1'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on:
      - self-hosted
      - ansible
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout current pull-request revision code
        uses: actions/checkout@v3

      - name: Set environment variables
        uses: ./.github/actions/set-env

      - name: Run deployment tasks
        uses: ./.github/actions/deploy
        with:
          environment: "${{ env.ENVIRONMENT }}"
          ansible_vault_password: "${{ secrets.ANSIBLE_VAULT_PASSWORD }}"
          intake: 'test'
          dry_run: true
